[project]
name = "project-hailml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "open-webui>=0.6.5",
    "peft>=0.17.1",
    "ray[serve]>=2.49.0",
    "torchvision>=0.23.0",
    "transformers>=4.55.4",
]
